name: API Documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml
          coverage: none
          tools: composer:v2

      - name: Install phpDocumentor
        run: |
          composer require --dev phpdocumentor/phpdocumentor
          
      - name: Generate Documentation
        run: |
          rm -rf _site/ venice-ai-php/
          mkdir -p _site/venice-ai-php
          vendor/bin/phpdoc -c phpdoc.xml
          if [ -d "venice-ai-php" ]; then
            cp -r venice-ai-php/* _site/venice-ai-php/
            echo "Documentation files:"
            find _site/venice-ai-php -type f
          else
            echo "Error: Documentation not generated"
            exit 1
          fi
          cp -f index.html _site/
          echo "Final site structure:"
          find _site -type f
          echo "Site directory structure:"
          ls -la _site/
          echo "Documentation directory contents:"
          ls -la _site/venice-ai-php/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4